### ISSUE TITLE
Incorporate new features from django-tenants

### ISSUE THREAD

**Issue by lorinkoz** [lorinkoz/django-pgschemas#10]
Review and incorporate these:

- [x] ~https://github.com/tomturner/django-tenants/pull/261/~
- [x] ~https://github.com/tomturner/django-tenants/pull/223/~
- [x] ~https://github.com/tomturner/django-tenants/pull/227/~
- [x] ~https://github.com/tomturner/django-tenants/pull/228/~
- [x] https://github.com/tomturner/django-tenants/pull/249/

The Django admin customizations are still out of the scope here.
The modification of the `TenantClient.login` feels out of scope, since this comes from a Django decision itself, it seems that this customization would be more appropriate to be carried out as part of test mocking.

**Comment by stemcc** [comment]
Does this library suffer from tomturner/django-tenants#249?

**Comment by lorinkoz** [comment]
@stemcc Maybe worse, I haven't ported the tenant file/template specifics.

**Comment by lorinkoz** [comment]
@stemcc I have ported the `TenantFileSystemStorage` from `django-tenants`. It's currently in `master` and should make it into the next release next week. The problem stated in the issue should be fixed here and there.
