### ISSUE TITLE
createrefschema error

### ISSUE THREAD

**Issue by dbill23** [lorinkoz/django-pgschemas#109]
I'm getting this error when running createrefschema. The error message doesn't make any sense to me. What names are clashing?

`(venv) C:\code\fin2>manage.py createrefschema
SystemCheckError: System check identified some issues:

CRITICALS:
?: (pgschemas.W004) Name clash found between static and dynamic tenants: {'public'}`

My settings looks like this...
`TENANTS = {
    "public": {  # always treated as a shared schema. Cannot be routed directly.
        "APPS": [
            "django.contrib.contenttypes",
            "django.contrib.staticfiles",
            "django_pgschemas",
            'customers',
        ],
    },
    "default": {  # represents all dynamic tenants
        "TENANT_MODEL": "customers.Client",
        "DOMAIN_MODEL": "customers.Domain",
        "APPS": [
            "django.contrib.auth",
            "django.contrib.sessions",
            "fin.apps.FinConfig",
            "users.apps.UsersConfig",
            'django_plotly_dash',
            'constance.backends.database',
            'constance',
            'django.contrib.admin',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'fontawesomefree',
            'bootstrap_modal_forms',
            'widget_tweaks',
            'crispy_forms',
            'flatpickr',
            'bootstrap4',
            'django_extensions',
            'rest_framework',
        ],
        "URLCONF": "mysite.urls",
        "CLONE_REFERENCE": "refschema",
    },
}

INSTALLED_APPS = []
for schema in TENANTS:
    INSTALLED_APPS += [app for app in TENANTS[schema]["APPS"] if app not in INSTALLED_APPS]

ROOT_URLCONF = TENANTS["default"]["URLCONF"]`

**Comment by lorinkoz** [comment]
Do you have a dynamic tenant (tenant in the database) with schema == 'public'?

**Comment by dbill23** [comment]
I have a schema named "public" in the database. I also have an entry in the Customers.client table with schema_name='public'.

**Comment by lorinkoz** [comment]
You shouldn't have schema names repeated, especially the "public" schema shouldn't be a dynamic tenant by default.

**Comment by dbill23** [comment]
@lorinkoz Thank you that solves it.
