### ISSUE TITLE
createrefschema does not carry over column_default values

### ISSUE THREAD

**Issue by ZipBrandon** [lorinkoz/django-pgschemas#129]
I created a template schema with `createrefschema`.  I then created a new tenant off that.  When I attempted to make a new migration for my project and migrate, it fails when it gets to the new tenant with 
```django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey" DETAIL:  Key (id)=(1) already exists.```

Investigating it I can see that the column defaults aren't carried over in Postgres.

**Comment by lorinkoz** [comment]
Could be a sequence problem. I am using https://github.com/denishpatel/pg-clone-schema/blob/master/clone_schema.sql for cloning schemas, but it's been a while since I last updated the script. Would you mind using the latest version of that script and check if the error resolves for you?

**Comment by ZipBrandon** [comment]
@lorinkoz : I deleted the previous functions in `public` and executed the new `clone_schema.sql` in `public` which created the procedures.  I had to modify `django_pgschemas/utils.py` (modifying line 206 to `cursor.callproc("clone_schema", [base_schema_name, new_schema_name, "DATA"])`) to call it with the new parameters that were added since you pulled it in.  Unfortunately it fails with the clone.  I have `citext` extension installed (https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/fields/#citext-fields) which resides in `public` but this clone_schema script attempts to find in my tenant schema. :( 



`InternalError at /admin/clients/client/add/
Action: Tables  Diagnostics: line=PL/pgSQL function clone_schema(text,text,cloneparms[]) line 676 at EXECUTE. 42704. type "new_schema.citext" does not exist
CONTEXT:  PL/pgSQL function clone_schema(text,text,cloneparms[]) line 2114 at RAISE`

**Comment by lorinkoz** [comment]
Thanks for creating the issue there! Keep me posted and I'll cut a pgschemas release including the new script as soon as it's fixed.

**Comment by lorinkoz** [comment]
Ref: https://github.com/lorinkoz/django-pgschemas/pull/130

**Comment by MichaelDBA** [comment]
clone_schema issue fixed: https://github.com/denishpatel/pg-clone-schema/issues/100
Was able to figure out the problem in clone_schema and fixed it.  Please get the latest clone_schema from:
https://github.com/denishpatel/pg-clone-schema

**Comment by lorinkoz** [comment]
That was fast! Thank you!

**Comment by MichaelDBA** [comment]
Thanks for using clone_schema for your project!
