### ISSUE TITLE
Reference for 4.2 minor version

### ISSUE THREAD

**Issue by alcad** [lorinkoz/django-pgschemas#143]
https://github.com/lorinkoz/django-pgschemas/blob/02506a65602297235dfa2ef09ec7db07f65a3052/pyproject.toml#L21

Maybe could be better to reference excluding next minor version and not for exclude all patch for actual minor:

`django = ">=4.0,<4.3"`

instead of

`django = ">=4.0,<=4.2"`

this way i can upgrade for 4.2.1, 4.2.2, etc

**Comment by lorinkoz** [comment]
Sorry for the silly bug.
