### ISSUE TITLE
Use psycopg2-binary instead of psycopg2 or make it an optional dependency

### ISSUE THREAD

**Issue by VaZark** [lorinkoz/django-pgschemas#148]
In cerrtains Macs building the psycopg2 package throws errors and it is easier to manage with the binary

It'd be great if we could choose between psycopg2 or psycopg2-binary at the project level or at least choose to ignore the psycopg2 dependency. (poetry does not seem to have any docs on sub-dependency override)

**Comment by lorinkoz** [comment]
Interesting point. We could move the dependency to the `--dev` group, so that is only required for local development, and otherwise assumed to be installed.

**Comment by VaZark** [comment]
That'd be perfect. 

Are there any hard dependency on psycogpg2? With v3.1 recently released.. it might make it easier for supporting multiple versions as well

**Comment by lorinkoz** [comment]
Sorry for taking so long, it's hard to be an open source maintainer in times of Tears of the Kingdom :P
