### ISSUE TITLE
Refactoring for v0.99

### ISSUE THREAD

**Issue by lorinkoz** [lorinkoz/django-pgschemas#196]
Refactor

- [x] Use contextvars instead of `asgiref.Local`
- [x] Move domain-related handling to `routing` module.
- [x] Make domain-related handling optional, together with all the related `TENANTS` settings.
- [x] Use `TenantModel.routing`
- [x] Implement middleware for session routing and headers routing
- [x] Move to `pytest` !!
- [x] Level up the typing game

more to come...

**Comment by ZipBrandon** [comment]
Looking forward to this! 😃

**Comment by lorinkoz** [comment]
Sorry for the looooong delay. Life (not Zelda this time) is keeping me busy!

**Comment by ZipBrandon** [comment]
@lorinkoz Cheers!

**Comment by ZipBrandon** [comment]
Honestly I'll have to investigate!  Are you able to summarize on the release notes since most things went to master? 

I had my own implementation of Headers for routing because I use Django as a backend and communicate to it from the frontend over an internal route. I'll move to your supported format.

**Comment by lorinkoz** [comment]
Ah, interesting.

> Are you able to summarize on the release notes since most things went to master?

I will, still figuring out how to do it because there are quite some breaking changes.

> I had my own implementation of Headers

Let me ask you here. What were you putting in the header? The schema name of the tenant, the id, or some other unique data?

**Comment by ZipBrandon** [comment]
I am putting the tenant PK, a UUID, in the header.

**Comment by lorinkoz** [comment]
Thank you.

So you'd say [this](https://github.com/lorinkoz/django-pgschemas/blob/master/django_pgschemas/routing/middleware.py#L149-L177) should work for you without further configuration?

**Comment by lorinkoz** [comment]
@ZipBrandon if one of these days you'd like to give a try to the v1 candidate, this is the place to start: https://github.com/lorinkoz/django-pgschemas/discussions/277
