### ISSUE TITLE
How to get current schema/ tenant?

### ISSUE THREAD

**Issue by simondrabble** [lorinkoz/django-pgschemas#46]
I have a number of celery tasks that (will) operate on individual tenants. I can write a wrapper to loop over these tasks, or use a request object to obtain the current tenant, but I'm curious about a general method for obtaining the contextually current tenant. This is especially useful for running such tasks from a management command - something like

```
./manage.py runschema my_command -s schema1  # starts, e.g., tasks.my_task.delay() to run within the celery process
```

`my_command` will fire off a task, but the task will of course run in a different process than the management command; so passing the tenant ID or schema name to the task will be required. How do I obtain the current tenant within my_command? I thought it would be on the connection but doesn't seem to be available there. I'm looking for something like this:

`SELECT current_schema();`

(from https://www.postgresqltutorial.com/postgresql-schema/)

**Comment by simondrabble** [comment]
Looks like my best approach is a raw query. Was hoping for something a little more robust, but I can work with it.

**Comment by lorinkoz** [comment]
If you're going to create a new command, you can subclass `TenantCommand`, `StaticTenantCommand` or `DynamicTenantCommand` (the last two scoping the allowed tenants). All three provide a `handle_tenant` method and receive a `tenant` argument.

https://django-pgschemas.readthedocs.io/en/stable/advanced.html#inheritable-commands

**Comment by simondrabble** [comment]
I somehow missed that, looks perfect!
