### ISSUE TITLE
Execution plan for management commands

### ISSUE THREAD

**Issue by lorinkoz** [lorinkoz/django-pgschemas#5]
Sometimes you want to run a command on all dynamic schemas, and for some reason the command halts before finishing. You don't want to start over again, how to "resume execution" and only run it on the missing schemas?

Is there any standard for storing execution plans? Any standard for the arguments one must use to play along with an execution plan?

**Comment by lorinkoz** [comment]
Since we have a multiproc executor, trying to manage shared state between processes via filesystem is a complex thing. I think managing state in database is more in line with the scope of the problem. This, however, will imply that `django-pgschemas` will have models of its own, and that the app itself must be placed in public APPS as a rule.

The idea would be then to create a model to store status of a command per dynamic tenant. The command would use the table data to determine which tenants are pending, in process, completed. Command should also clean itself after executing.

We need an argument to signify that an execution plan is to be used, and another to signify that the execution plan is to be started fresh even if a partially executed plan is found. Thinking of:

- `-ps` `--plan-start` For forcibly starting a new execution plan
- `-pr` `--plan-resume` For trying to resume an existing plan, or start a new one otherwise.

The lack of any of such arguments would mean do not use execution plan. And if both arguments are passed, the weakest one would be in place (resume in this case.)

**Comment by lorinkoz** [comment]
We might also need a `clearplans` command, to delete plans from database. It would filter by command and status.

**Comment by lorinkoz** [comment]
@tomturner Can I get your input on this idea/approach?

**Comment by lorinkoz** [comment]
Nevermind, whoever wants to do this, let them use an external queue.

**Comment by j2l** [comment]
> Nevermind, whoever wants to do this, let them use an external queue.

May I ask how?

**Comment by lorinkoz** [comment]
The original idea of this ticket was to create a consistent order for running certain commands on certain tenants/schemas, so that if the process stopped for some reason, it could be resumed without restarting. However this is far beyond the scope of a package like this. In order to implement this it would make more sense to:

1. Generate the list of tenant/schemas where the operation must be run
2. Store the list in any external storage (task queue)
3. Have a task runner pick up from the list and execute the task

This is the typical thing one use task queues and runners for (think celery, dramatiq, etc.)
