### ISSUE TITLE
Custom Apps dont get migrated

### ISSUE THREAD

**Issue by mcroni** [lorinkoz/django-pgschemas#6]
Following the docs,  and implemented the `TENANTS` dict which i later on applied the `python manage.py migrateschema -s public` and `python manage.py migrateschema` respectively but the apps i created do not show in either schemas including the shared app which hinders me from creating a client with the django shell. 

` TENANTS = {
            "www": {

        "APPS": [
            'django.contrib.admin',
            "django.contrib.auth",
            "django.contrib.sessions",
            "rae_profile",
        ],
        "DOMAINS": ["raedarr.com"],
        "URLCONF": "rae_profile.urls",
    },
    "public": {
        "APPS": [
            'django.contrib.admin',
            "django.contrib.auth",
            'django.contrib.sessions',
            "django.contrib.contenttypes",
            "django.contrib.staticfiles",
            "django_pgschemas",
            "pwa",
            "shared_app"
        ],
        "TENANT_MODEL": "shared_app.Client",
        "DOMAIN_MODEL": "shared_app.Domain",
    },
    "default": {
        "APPS": [
            'django.contrib.admin',
            "django.contrib.auth",
            "django.contrib.sessions",
            'django.contrib.sites',
            "post_office",
            'hr.apps.HrConfig',
            "chat.apps.ChatConfig",
            'crm',
            'payroll.apps.PayrollConfig',
            'invoice.apps.InvoiceConfig',
            'benefits.apps.BenefitsConfig',
            'transport.apps.TransportConfig',
            'leave.apps.LeaveConfig',
            'estate.apps.EstateConfig',
            'attendance.apps.AttendanceConfig',
            'revenue.apps.RevenueConfig',
            # 'allauth',
            # 'allauth.account',
            # 'allauth.socialaccount',
            # 'allauth.socialaccount.providers.asana',
            # 'allauth.socialaccount.providers.google',
            # 'allauth.socialaccount.providers.linkedin',
            # 'allauth.socialaccount.providers.linkedin_oauth2',
            # ...
        ],
        "URLCONF": "rae_profile.urls",
    }
}`

Thanks

**Comment by lorinkoz** [comment]
Could you try erasing the database/schemas and starting over again. Let me know if this works. I also see other unrelated things in your config that could cause problems later. Up for switching over to gitter.im? These things would be best discussed in a chat.
