### ISSUE TITLE
`DROP FUNCTION IF EXISTS` drops function in another schema too

### ISSUE THREAD

**Issue by yetanotherion** [lorinkoz/django-pgschemas#62]
### How to reproduce
A db with two schemas:
- *public*
- *reference_tenant*

Setup the following migration script
```python
from django.db import migrations
from django.db.migrations import RunPython

create = """
DROP FUNCTION IF EXISTS reproduce_error();
CREATE OR REPLACE FUNCTION reproduce_error()
    RETURNS TEXT AS
$func$
BEGIN
    RETURN (select version());
END
$func$ LANGUAGE plpgsql;
"""

delete = "DROP FUNCTION IF EXISTS reproduce_error();"


def forwards_func(_, schema_editor):
    schema_editor.execute(create, params=None)


def reverse_func(_, schema_editor):
    schema_editor.execute(delete, params=None)


class Migration(migrations.Migration):
    dependencies = [
        ("business", <former_script>),
    ]

    operations = [RunPython(forwards_func, reverse_func)]
```

```shell
python manage.py migrate business --schema public
```

The `reproduce_error` function is in the *public* schema.

```shell
python manage.py migrate business --schema reference_tenant
```
The `reproduce_error` function:
* is in the *reference_tenant* schema,
* **is not** in the *public* schema anymore.

### Expected behavior

The `reproduce_error` function:
* is in the *reference_tenant* schema,
* **is** in the *public* schema.

### Additional info
By removing `DROP FUNCTION IF EXISTS reproduce_error();` in the `create` above, the issue is not reproduced.

(In case further interactive discussions will be necessary, the problem was written at https://gitter.im/django-pgschemas/community too)

**Comment by lorinkoz** [comment]
👋🏼 

The "business" app is listed under which tenant configuration?

**Comment by yetanotherion** [comment]
Hi @lorinkoz! It is in both (reference_tenant and public) tenants.

**Comment by yetanotherion** [comment]
After a discussion with a colleague that setup the configuration of the app that is impacted by this issue, 
I think we root caused the issue thanks to your question.

### Root cause
The bug reproduction scenario comes from an incorrect setup: a django app, 
- not setup as mult-itenant, 
- that has 
```python
...
TENANT_APPS = [..., "business.apps.BusinessConfig"]
TENANTS['default']['CLONE_REFERENCE'] = 'reference_tenant'
TENANT['public']['APPS'].extend(TENANT_APPS)
...
```

In the end, we consider that this setup is wrong. We managed to fix our issue by removing the `CLONE_REFERENCE` key when the app is setup in a non multi-tenant configuration.
```python
...
TENANT_APPS = [..., "business.apps.BusinessConfig"]
TENANT['public']['APPS'].extend(TENANT_APPS)
...
```

If that's fine with you, we propose that we close this issue as the bug was in our setup.

Sorry for the noise and thanks again for this very precious question!

**Comment by lorinkoz** [comment]
No worries, and glad you solved the problem 😄 

For the record, I wasn't able to reproduce the error on my end. Raw SQL in migration code is implicitly tied to the application where the migration is, and that, in turn, corresponds to one or many schemas based on the TENANT configuration.
