### ISSUE TITLE
Reverse seems to fail in some instances

### ISSUE THREAD

**Issue by OmenApps** [lorinkoz/django-pgschemas#8]
I'm still digging into this, but it looks like when I use LoginRequiredMixin, the reverse for the login url returns incorrect value under certain circumstances. Here's the background:

settings.py

    LOGIN_URL = "user_login"  # or whatever your login url name might be

urls.py (simplified)

    /home/ goes to a simple TemplateView
    /about/ goes to the same TemplateView, with LoginRequiredMixin
    /accounts/ goes to the accounts app urls

accounts/urls.py

    /login/ goes to the login authentication view, url name: "user_login"

I have set up two tenants.

Client1

    domain: app.mydomain.com
    folder: client1
    schema_name: client1

Client2

    domain: app.mydomain.com
    folder: client2
    schema_name: client2

If I start the server and go any view for Client1 (**app.mydomain.com/client1/home/** or **app.mydomain.com/client1/about/**), all works well. 

Now, if I go to home for Client2 (**app.mydomain.com/client2/home/**), no problem.

But as soon as I go to a view with LoginRequiredMixin (**app.mydomain.com/client2/about/**), I get problems. Instead of going to **app.mydomain.com/client2/accounts/login/** I'm getting redirects to **app.mydomain.com/client1/accounts/login/**

This same thing happens in reverse if I start the server, go to a Client2 url, and then try to go to a Client1 url that uses LoginRequiredMixin. (goes to **app.mydomain.com/client2/accounts/login/** rather than the expected **app.mydomain.com/client1/accounts/login/**)

I verified by copying LoginRequiredMixin to my own project and doing something like this within the get_login_url method (I know, debugging by print statement is evil, but it's easy to replicate):

    def get_login_url(self):
        """
        Override this method to override the login_url attribute.
        """
        login_url = self.login_url or settings.LOGIN_URL
        print("get_login_url login_url: ", str(login_url))
        print("get_login_url reverse(login_url): ", reverse(str(login_url)))
        print("get_login_url schema_name: ", connection.schema.schema_name)

        if not login_url:
            raise ImproperlyConfigured(
                "{0} is missing the login_url attribute. Define {0}.login_url, settings.LOGIN_URL, or override "
                "{0}.get_login_url().".format(self.__class__.__name__)
            )
        return str(login_url)

Result (after going to a url for the second client from the initial example above):

    get_login_url login_url: user_login
    get_login_url reverse(login_url): /client1/accounts/login/
    get_login_url schema_name: client2

Any recommendations? Anyone else experiencing this?

**Comment by OmenApps** [comment]
In order to simplify things and make sure I'm not crazy, I went back to the sandbox example project with the following modifications:

app_tenants/views.py

    from django.views.generic.base import TemplateView
    from django.contrib.auth.mixins import LoginRequiredMixin

    class HomePageView(TemplateView):
        template_name = "app_tenants/home.html"

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            return context


    class AboutPageView(LoginRequiredMixin, TemplateView):
        template_name = "app_tenants/home.html"

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            return context



app_tenants/urls.py

    from django.urls import path
    from django.contrib.auth.mixins import LoginRequiredMixin
    from .views import HomePageView, AboutPageView


    urlpatterns = [
        path("home/", HomePageView.as_view(template_name="app_tenants/home.html"), name="home"),
        path("about/", AboutPageView.as_view(template_name="app_tenants/home.html"), name="about"),
    ]


app_tenants/templates/app_tenants/home.html

    <!doctype html>
    <html>
        <head>
            <meta charset="utf-8">
            <title>Basic Site Template</title>
        </head>

        <body>
            <h1>TEST</h1>
        </body>
    </html>


Created 2 tenants:

    client1 = Tenant.objects.create(schema_name="client1")
    Domain.objects.create(domain="app.watervize.net", folder="client1", tenant=client1, is_primary=True)

    client2 = Tenant.objects.create(schema_name="client2")
    Domain.objects.create(domain="app.watervize.net", folder="client2", tenant=client2, is_primary=True)

I can go to **app.mydomain.com/client1/home/** or **app.mydomain.com/client2/home/**

When I go to  **app.mydomain.com/client1/about/** or **app.mydomain.com/client1/about/** I get a 404, with the project trying to redirect to **app.mydomain.com/accounts/login/?next=/client1/about/**. There is no tenant for app.mydomain.com, so this fails. It should be **app.mydomain.com/client1/accounts/login/?next=/client1/about/**, right?

I feel like I'm moving backward. Any ideas?

**Comment by lorinkoz** [comment]
Interesting case. Thanks for reporting. I'll take a look.

**Comment by lorinkoz** [comment]
I was able to confirm the bug. Let's play a possible fix.

Try calling `clear_url_caches()` in this line:

https://github.com/lorinkoz/django-pgschemas/blob/ee631ea2a8041c1d44b3abcca2035314d9df00a1/django_pgschemas/middleware.py#L65

import the function `from django.urls import clear_url_caches`

---
Looks like the url resolver caches the url prefixes for performance, but since we're switching tenants the cache is only making the first tenant permanent for all `reverse` calls. The official fix should be clearing the cache in the DB backend, so as to keep reverse working not only on the request/response flow.

As a side note, on certain contexts, the `reverse` call might not use the right url resolver by default. I found a case in one of my projects where calling `reverse` in a middleware doesn't effectively prefix the url with the tenant, unless I explicitly pass `request.urlconf` as second argument to `reverse`. Will investigate this further.

**Comment by OmenApps** [comment]
Interesting. I figured something was getting cached, but I didn't know enough about url resolvers to narrow it down.

That seemed to fix things on both the sandbox project, and on my real project. In the case of moving the solution to the DB backend, does it make sense to place clear_url_caches() at the end of set_schema(), so that the cache is cleared on every schema change? Doing the work there also corrected the issue for me, but maybe there is a better place to do this? Is there a drawback to doing it on every schema change (e.g. when changing to public)?

I'll keep an eye out for the other case you mentioned as well.

**Comment by lorinkoz** [comment]
@OmenApps Please let me know if anything else comes up in the process. I will wait for some days before releasing a new version with these changes.

**Comment by OmenApps** [comment]
Great. Updating my projects to use the latest version. Will test things out over the next couple days and let you know.
