### ISSUE TITLE
Dynamically created urlconf not properly incorporating all definitions from original

### ISSUE THREAD

**Issue by kptac** [lorinkoz/django-pgschemas#9]
I'm using a single domain with tenant folders. Ex. app.domain.com/tenant1, app.domain.com/tenant2, etc.

I use this https://docs.djangoproject.com/en/2.2/ref/urls/#handler404 to have a different 404 view.

After setting up django-pgschemas, I've noticed that handler404 works when I visit app.domain.com/asdadas, but if I get a 404 response with tenant folder, the handler404 view is not used. For example, when I visit app.domain.com/tenant1/asdasdas, it shows the default page not found error.

Please advice.

**Comment by lorinkoz** [comment]
Thanks for reporting. Let me take a look and I will get back to you.

**Comment by lorinkoz** [comment]
@kptac Are you able to test your code with the latest master? I just pushed a possible fixed and would like your input before making a formal release.

**Comment by kptac** [comment]
@lorinkoz, just tried it, seems to have broken another app that I've been using - [django-cruds-adminlte](https://github.com/oscarmlage/django-cruds-adminlte). Which works fine on v.0.3.2.

![image](https://user-images.githubusercontent.com/7469885/65713540-73994f00-e0aa-11e9-8b91-4830bfb2f4a1.png)

**Comment by lorinkoz** [comment]
Okay, thank you. Let me try a different approach that doesn't actually import the urls module in the middleware. This could take some time, stay tuned.

**Comment by lorinkoz** [comment]
@kptac It's quite hard for me to determine the cause of the new bug without a configuration similar to your project. Do you think you could setup the simplest possible project that uses `django-cruds-adminlte` in the same way you're using it? I have never used that package before and therefore I lack the knowledge to properly guess where the problem is.

**Comment by kptac** [comment]
Hi Lorinkoz, actually I decided not to continue with this package at the moment, there were some other issues too that I discovered. Mainly template caching with folders that held me back. Also the tenant object in requests had an empty folder variable that was bothering me. I believe there's a lot of work pending on the folder-based tenants side, and I was running behind on my project. So I moved on with django-tenants for the time being. I will definitely revert back to this project at a later stage, and try to give further input.

Also, with all due respect, the way you handle issues by committing straight to master branch makes me a bit uncomfortable to work with this project. There's no review process or tests in place. There's a bit of organization that needs to be done here.

I just thought I will share my 2 cents. Thanks and keep the great work.

**Comment by lorinkoz** [comment]
Hi @kptac. Thanks for your feedback.

If you have time, please provide me with some explanation regarding the problems you mention with "template caching with folders". I haven't used that myself with django-tenants so I can't properly relate.
Thanks for reporting the emptiness of `request.tenant.folder`. Fixed! :)
As for the workflow, you're right and thanks for sharing your thoughts.

If you feel like investing some time in pgschemas in the near future, you can use it mixed mode, that is, mainly with subdomain routing while also making the tenants available through folder routing. pgschemas would benefit from the feedback that comes with real projects like yours, and the interation with other django packages.

If possible, please let me know which issues are holding you back from using pgschemas, as of now, with subdomain routing alone. If we can get those addressed, that would pave the path for you and other developers to jump on and help me polish the folder routing.

**Comment by kptac** [comment]
> If you have time, please provide me with some explanation regarding the problems you mention with "template caching with folders"

Hi @lorinkoz - what I noticed was that template caching done for a specific tenant, is not respected. You can test this with a simple template (in my case it was side menu) with all URLs being generated with a reverse lookup. When I changed tenants, the menu links were of another tenant. I was logged into both tenants, so maybe that could be an issue there, not sure? I didnt test further, and just switched packages right then.

> Thanks for reporting the emptiness of request.tenant.folder. Fixed! :)

Excellent

> If possible, please let me know which issues are holding you back from using pgschemas, as of now, with subdomain routing alone.

I will try to dive into this in 2 weeks or so once I'm done with the current project Im working on. It's an MVP and I need to launch it ASAP, that's why I couldn't hold longer. But for sure, I will try to come back again to this package soon, as I really like the folders concept, and also the static apps feature.

Keep up the good work. A solid multitnenant package is what Django needs right now. django-tenants owners are very specific about their own use cases and not open to a lot of new functionalities at this stage. If I get a good project in the future, I will see if I can get a sponsor for further development here.

**Comment by lorinkoz** [comment]
Hey @kptac, if you're still interested/available to give this a try, please download the latest code in master and see if by returning `get_from_lazy_module()` instead of `get_from_spec()`, everything works good and your integration with `django-cruds-adminlte` doesn't break. Thanks!

https://github.com/lorinkoz/django-pgschemas/blob/833ae6e3d6d0e0a05b8af03f7c5c8d1aa7e6b6cb/django_pgschemas/urlresolvers.py#L100
